### ISSUE TITLE
Incompatible with controllify

### ISSUE THREAD

**Issue by BigWrinklySack** [Wilyicaro/Legacy-Minecraft#101]
the game crashes. i have no idea why.

I'm on macos high sierra

**Comment by DanielMC101** [comment]
they plan on adding controller support in the future

**Comment by BigWrinklySack** [comment]
> 

Oh, although using Controllify would be good alternative until full support is added

**Comment by Wilyicaro** [comment]
Midnight controls work fine, at least last time I tested, I'm not going to work on compatibility with specific controller mods, as I'll add native controller support, as @DanielMC101 said.

**Comment by BigWrinklySack** [comment]
> Midnight controls work fine, at least last time I tested, I'm not going to work on compatibility with specific controller mods, as I'll add native controller support, as @DanielMC101 said.

i cant use midnight controls cus it has a glitch, (I'm on mac) where i cant move the camera (with mouse) or mine (with any input) , and it happens when i change the settings. it's really weird. and makes it unplayable. i have to delete the settings file to reset and the default settings are way too clunky.

**Comment by AgentMindStorm** [comment]
It may be easier to add compatibility with other controller mods instead of adding native controller support. Controller support is a real rabbit hole: you have to consider every menu, every brand of controller, every glyph for each controller's buttons, the implementation of radial and axial deadzones, a full set of rebindable keys... it gets messy. It would probably be more difficult to update the mod in the future if you added native controller support, as opposed to allowing other controller mods to work with your mod.

**Comment by Wilyicaro** [comment]
> It may be easier to add compatibility with other controller mods instead of adding native controller support. Controller support is a real rabbit hole: you have to consider every menu, every brand of controller, every glyph for each controller's buttons, the implementation of radial and axial deadzones, a full set of rebindable keys... it gets messy. It would probably be more difficult to update the mod in the future if you added native controller support, as opposed to allowing other controller mods to work with your mod.

The biggest issue with compatibility with some controller mods will be the workarounds I'll have to do to, accurately recreate the LE layout and adapt the mod code to my interfaces, and obviously the many conflicts/bugs there will be. In the end I will only use the mod base, as I recreated and adapted most of the things for LE, not to mention the issues of my mod being for fabric and forge, the backports etc.

**Comment by Vladivaston** [comment]
Is it theoretically possible to just add controller mod support for Fabric and make an In-House implementation for Forge? In-House controller support will undoubtedly cause conflictions with other mods unless done right. As AgentMindStorm mentioned its also very hard to implement

**Comment by Wilyicaro** [comment]
A native implementation only for forge and a compatibility with Controlify or Midnight Controls will make the development a lot more difficulty and it doesn't make sense.
And no, it's not very hard to implement, mainly because unlike other controller mods, it should be simple and similar to LE as possible, as it doesn't have a lot of options, and I already have experience with this

**Comment by Vladivaston** [comment]
My only concern is mod compatibility, regarding specifically mods that have a World Preset/Configuration menu (eg. Modern Beta)

**Comment by Wilyicaro** [comment]
This is a simple compatibility, as all mods have screens based on minecraft methods, and with the arrow navigation support from 1.20, there are no problems, only before 1.20 that this is bit annoying, but nothing to worry about.
And about steam deck, the APIs used for Controller compatibility are mainly universal, and with its built-in controller in Linux, that isn't a problem either.

**Comment by Vladivaston** [comment]
I see, thank you for the very quick responses. I look forward for the 1.20.1 backport sometime in the future as mentioned in #2 . Great mod!
