### ISSUE TITLE
World pre-load menu doesnt appear for already-generated worlds / Player nickname boxes connect to each other when in multiplayer

### ISSUE THREAD

**Issue by UMFD** [Wilyicaro/Legacy-Minecraft#109]
For some reason, and no matter how hard i tried, every time i try to go into a pre-generated world, it doesnt show me that pre-load menu, with gamemode, difficutly, resourcepack, open to lan etc. That is not how it is on legacy, and its also less convinient if i want to host a LAN game for my friend to join while we are in school. Also the player nickname boxes for some reason connect to each other? (even though they shouldnt, might be an issue with the larger playercount)

[Pre-load menu] Intended behavior:
https://github.com/Wilyicaro/Legacy-Minecraft/assets/101548356/dca71bc4-072c-4999-a5fc-250d6897ba01

[Pre-load menu] Actual behavior:
https://github.com/Wilyicaro/Legacy-Minecraft/assets/101548356/4aa79c10-4377-4d63-968c-ebcbc8313347

Player nickname boxes connecting with each other:
![2024-02-21_08 37 11](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101548356/307197c4-2d3b-46e3-a9d8-b95c25fe7d58)
![2024-02-21_08 36 59](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101548356/28a4e0b3-45c9-4195-ac30-f96e875ce686)

**Comment by UMFD** [comment]
also this might not be appropriate/inconvinient to put here, but could you please let vivecraft work with this mod? i would be so happy if i could enjoy minecraft with this mod in VR

**Comment by Wilyicaro** [comment]
You probably have the Load Save Directly option enabled, this obviously disables the Load Save screen, making loading significantly faster.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/6a754826-5ec8-418c-bbfd-4295f016ac29)

About the nickname boxes issue, this is probably a specific graphical implementation problem, I'm not an expert on this, but since on all the computers I've tested the mod didn't have this problem, I conclude that's it
![2024-02-21_15 21 32](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/117512ec-2b78-4c5b-8d72-5c3930b7c133)
