### ISSUE TITLE
Feature Request - Toggle each menu separately

### ISSUE THREAD

**Issue by Pedro270707** [Wilyicaro/Legacy-Minecraft#11]
Allow players to toggle each menu separately. For instance, you're currently able to disable the Creative inventory, but not the anvil inventory. Mainly for containers, but you could also do that in screens like the title screen or the game menu.
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/89267077/3218e937-0793-440a-a9cd-f497bfe9d964)

**Comment by Wilyicaro** [comment]
I added the Legacy Creative Tab option because of the other mods tabs, which can't be adapted well, but I think if you to play with Legacy4J, you want an experience as similar as possible to Legacy Edition, and add a option to disable each menu isn't easy and unfeasible, mainly for containers, that pratically only the appeareance was modified, with some exceptions, such as villager trades and the creative tab.
