### ISSUE TITLE
Certain Interfaces causes big fps drops

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#147]
Whilst Minecraft does natively lower fps in container screens to save resources, the latest version of this mod significantly decreases the frames on certain screens. The two in which I've noticed the irregularity is are the crafting interface screen and the mod screen. I have attached pictures of the fps in certain screens below:

Normal game fps:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/7ea8efad-2969-4743-8c85-19eab283668d)

Inventory fps(Normal decrease):
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/3d9122fb-3cce-4c3f-be01-332f528f918b)

Crafting Interface decrease(Irregular decrease):
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/74498a5b-d132-4cf9-a049-b9eb7bb0c888)

Classic Crafting Interface(Normal Decrease):
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/7e5f28c4-cb1c-40df-ae4e-7d63662f4474)

Creative Inventory Screen(Normal Decrease)::
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/984417c8-2c49-479b-a62a-b1bb36a20792)

Mod Screen(Irregular Decrease):
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/95002149/e3559221-89b0-4e21-b6d7-3d21b924549b)

I'm not so sure what about the Crafting Interface screen causes a drop, since the Creative Screen which draws many more images is lowered in a reasonable manner, but this has only started as of recently with the latest version.

**Comment by Wilyicaro** [comment]
Yes, I'm aware of this, and most of this performance drop is due to the game's poorly optimized rendering. To be more specific, the Crafting Interface always checks if you can craft the items on the screen, which causes a certain loss of performance, and has translucent items most of the time, along with the mods screen that has the tooltip box which is also translucent, and this translucency is mainly responsible for this drop in FPS, and there is not much point in changing the texture, due to the fact that it is enabled in the code
