### ISSUE TITLE
Mod-exclusive settings do not save

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#150]
Whenever I play, the mod exclusive settings(HUD Size, Interface Opacity and Distance, etc) aways revert back to default value, meaning I have to switch every time. This could probably be fixed with a config implementation,.

Also, are certain console skin types like the Yoda and Ewok skins being smaller and a big nose banjo Kazooie skins be implemented with the skin library?

**Comment by Wilyicaro** [comment]
> Whenever I play, the mod exclusive settings(HUD Size, Interface Opacity and Distance, etc) aways revert back to default value, meaning I have to switch every time. This could probably be fixed with a config implementation,.
> 
> Also, are certain console skin types like the Yoda and Ewok skins being smaller and a big nose banjo Kazooie skins be implemented with the skin library?

This is a bug, some options aren't saving, not just the "exclusive settings", it's not a lack of a config, it'll be fixed in the next version.
About the Skin Packs, probably at the beginning there will only be standard skins, to speed up the development process, as just adding skins with customized models would be simple, but I plan more elaborate support with resource packs.
