### ISSUE TITLE
Incompatibility with Polytone

### ISSUE THREAD

**Issue by omo50** [Wilyicaro/Legacy-Minecraft#187]
Game crashes on startup with the mod. https://modrinth.com/mod/polytone

**Comment by Cixon** [comment]
forge and fabric versions of L4J appear to be incompatible. unfortunately, @Wilyicaro mentioned in a similar ticket that it’s not possible due to a mixin issue.

hopefully we can see a patch from either polytone ([ticket](https://github.com/MehVahdJukaar/polytone/issues/42)) or possibly through @Wilyicaro .

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
