### ISSUE TITLE
Flying sprinting in creative mode on blocks can cause to slow down

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#235]
Happens in latest version

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/7c294281-5685-4fca-b354-498a393fd65c

**Comment by Wilyicaro** [comment]
This has already been corrected, this slowness is caused by the "impact" when you descend, then it returns to normal flight speed, it is impossible to have greater precision due to the delta movement, which maintains this impact for a while, and which is not present in LE probably (I didn't look at the source code, so I can't say)
