### ISSUE TITLE
Feature Request - Vanilla Java Creative Mode Tabs as a toggle instead 

### ISSUE THREAD

**Issue by Chilly-roll** [Wilyicaro/Legacy-Minecraft#27]
Title says it all. (Not to be confused with the legacy creative toggle) It's a little redundant to have Java's creative tabs available as-is when the legacy ones already cover what they do (outside of operator tab) so perhaps introduce it as a toggle in User Interface so people can switch between the two _without_ disabling the legacy creative screen altogether?

I dunno if this even makes sense as a toggle, but I don't think it makes sense to have both legacy and java's creative tabs available at the same time except for the operator tab

**Comment by Wilyicaro** [comment]
I think the Legacy Creative Screen toggle actually makes sense, because the LE Creative Screen isn't made for keyboard and mouse, so it doesn't have search or a filter option, and I myself had difficulty finding certain things quickly in the interface I created lol.
About the java creative tabs toggle, at first I thought about it, now I think it's almost useless, just press RIGHT one more time to access the other mods' tabs.
