### ISSUE TITLE
Game Crashes on macOS Monterey and Sonoma

### ISSUE THREAD

**Issue by FMRG7009** [Wilyicaro/Legacy-Minecraft#323]
I am not sure whether it affects all versions of macOS, yet I do know that it crashes on these versions of the Operating System. It occurs on the latest version of the software.

**Comment by ivabus** [comment]
It is crashing because Legacy4J embeds libsdl4j which embeds SDL2 shared libraries for windows and linux only. I got it to work by showing SDL2 from homebrew via DYLD_LIBRARY_PATH environment variable.

Steps:
1. Install homebrew (<brew.sh>)
2. Install SDL2 from homebrew (`brew install sdl2`)
3. Set up additional environment variables through your launcher (Prism Launcher can do it, I don't know about others) like this: DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/sdl2/2.30.2/lib/
4. Try to run the game

<img width="966" alt="Снимок экрана 2024-05-15 в 16 54 47" src="https://github.com/Wilyicaro/Legacy-Minecraft/assets/71599788/f827cb02-fd26-47c3-8904-9b59ece06cdc">

**Comment by FMRG7009** [comment]
How would I add it into Environment Variables?

**Comment by ivabus** [comment]
If you’re using Prism Launcher (or any MultiMC based launcher) environment variables settings are available in the “settings” tab in instance settings

**Comment by Wilyicaro** [comment]
Fixed in version 1.6.4, thanks for reporting.
