### ISSUE TITLE
Enchancement: old console legacy skins used to be able to have the ears like Deadmou5 

### ISSUE THREAD

**Issue by A7e3** [Wilyicaro/Legacy-Minecraft#342]
You should make it so every skin can have ears like Deadmou5 is able to because old consoles legacy skins as show here:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/78892259/2e538a4f-108b-4158-826f-e059994e478a)

the Enderman and some other skins are able to have a party hat or some kind of headband obviously this wouldn't work for other players and just for you either client side or for people on this mod but it would be a cool addition

**Comment by Nerpx** [comment]
I also notice the wolf was also able to have a snout idk how you would make this because obviously the minecraft java edition skins manager is entirely most likely different then the console legacy skins manager so idk but these things even if it was just the ears part of the skin on head would be a great addition to have when the skin changer comes out so people can experience all of the old skins packs and not have to remove the ones with these custom stuff.

**Comment by Wilyicaro** [comment]
Unfortunately, suggestions need to be made on the Legacy4J Discord server in order to better organize GitHub for _issues_ and incompatibilities only (please note that suggestions prior to the creation of this server will be kept)
