### ISSUE TITLE
Incorrect/outdated description for tuff block

### ISSUE THREAD

**Issue by bugsbugsbugsLCE** [Wilyicaro/Legacy-Minecraft#363]
The description says that tuff is generated in amethyst geodes, which is false. Before 21w07a tuff indeed generated in amethys geodes but in 21w07a it was changed to generate with smooth basalt. Idk when the description was written. Maybe during the 1.17 snapshot phase? There are also many items that currently have no description such as buttons saplings, leaves, flower pots, spawn eggs, charcoal, pottery sherds, mossy cobblestone wall, hanging signs, banner patterns, wooden fences, infested blocks, nylium, quartz blocks and its varians, wooden doors and trapdoors, fence gates, terracotta.

![2024-05-17_17 54 55](https://github.com/Wilyicaro/Legacy-Minecraft/assets/166852932/ffa0b7a1-be75-494b-9714-047404deb29c)

**Comment by Wilyicaro** [comment]
I wasn't the one who wrote the descriptions, it was probably just a mistake, because from what I saw they were written from 1.18 onwards

**Comment by Wilyicaro** [comment]
Many items still don't have tips simply because there are _too many_, and in reality they at least have a translation, but I just forgot to do tip overrides for them.
If you don't want to wait for the next update you can add them yourself
https://github.com/Wilyicaro/Legacy-Minecraft/wiki/Predicate%E2%80%90Based-Manager#tip-overrides
