### ISSUE TITLE
Music doesn't switch when going through nether and end dimension.

### ISSUE THREAD

**Issue by DanielMC101** [Wilyicaro/Legacy-Minecraft#396]
Happens in current version 1.6.5

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/1eda9ecc-fca9-41ae-8035-74bffc237117

https://github.com/Wilyicaro/Legacy-Minecraft/assets/39068731/97833fa3-c871-43d9-882c-d4ade77d4f67

**Comment by DanielMC101** [comment]
turns out, it also keeps playing the ambient sound

**Comment by Wilyicaro** [comment]
As I always say, this is not an issue, it's a parity suggestion, this is expected, anything that changed the music when changing levels was removed.
This change is not even in the changelog because it's not complete, the focus of the update was another

**Comment by DanielMC101** [comment]
@Wilyicaro oh, why was it removed if u don't mind asking?

**Comment by Wilyicaro** [comment]
Because there is no difference between changing levels or dimensions (in this case, entering a world is also considered a level change), in the code they are the same thing, that is, it was necessary to remove this stop from the sounds to be able to make the menu music continue to play even after entering a world, but now it is necessary put a way to stop the sound when the player is on one level, and goes to another
