### ISSUE TITLE
Villager trade UI can't scroll past the end, not all trades can be used.

### ISSUE THREAD

**Issue by Un1q32** [Wilyicaro/Legacy-Minecraft#424]
In this video, the villager has a mending trade but it can't be accessed with the legacy UI

https://github.com/Wilyicaro/Legacy-Minecraft/assets/57970114/27c69a51-d491-4446-91d2-89d8a0c16cdb

**Comment by Wilyicaro** [comment]
The Merchant Interface was not designed to have more than 10 trades (it clearly doesn't even have space for a scroll), I don't know if it should do that, but anyway this is a bug in version 1.20.6-1.6.7, villagers are opening twice as many trades on each level reached, this will be fixed in the next version.
