### ISSUE TITLE
Can't see master trades when trading with villagers

### ISSUE THREAD

**Issue by TeleostSaturn17** [Wilyicaro/Legacy-Minecraft#461]
I find it pretty annoying that I can't see the master trades from villagers when using this I think this could be fixed with a scroll bar to scroll to the trades that are not shown

**Comment by Wilyicaro** [comment]
You certainly used the mod in a world where you didn't use it, this is not recommended due to mechanics like this, which are changed by it. (if it wasn't that, you used it in a version of the mod where there was a bug where Villagers unlock twice as many trades) 
Villagers and Wandering Traders normally have a maximum of 10 trades, without modifications or bugs, so the default interface doesn't show more than that, I may or may not change this in the future, if you really want to do these trades, enable Classic Crafting
