### ISSUE TITLE
[Bug/Glitch] Autosave preference not saving on game restart

### ISSUE THREAD

**Issue by Cjnator38** [Wilyicaro/Legacy-Minecraft#516]
### Legacy4J Version

1.21-1.7.2

### Mod Loader Version

Fabric Loader 0.15.11

### Bug/Glitch Occurrence Context

Enabling autosave in a world (cannot through slider) works, but only for the current game session. Restarting the game causes the autosave to become disabled again. Occurs on standalone L4J+Architectury+Fabric API, as well as Re-Console 0.6.0 with FastQuit disabled.

### What happened wrong?

Autosave disabling on game restart

**Comment by Raysofdoom2665** [comment]
I can vouch for this on 1.20.1-1.7.1 for forge as well.

**Comment by WC54** [comment]
I have the same problem too cjnator38. Legacy4J can sometimes use alot of memory when saving the world (manually) that it can cause minecraft to crash and not fully saving the world. Usually happens when playing for 1-2 hours with autosaving disabled. It happend to me once and my inventory was the only thing that was not saved. Everything else in the world was saved. 
It is fast and easy to enable autosaving after booting minecraft, but it's just so boring to do that for every time i boot minecraft with the legacy4j mod.

I hope that the developers of Legacy4j fixes this bug ASAP.

**Comment by WC54** [comment]
The creator of Legacy4j has fixed the autosave problem in the new 1.7.3 update!
