### ISSUE TITLE
Can't craft wind charge with breeze rod in legacy craft system

### ISSUE THREAD

**Issue by schlime9k** [Wilyicaro/Legacy-Minecraft#528]
As stated in the title, After aquiring a breeze rod, they can't be crafted into wind charges within the legacy craft UI and you need to change the interface to the normal UI in order to craft the charges.

**Comment by Wilyicaro** [comment]
Every non-custom recipe is present "legacy crafting system", just enable the Display Vanilla Tabs.
It's practically impossible for me to add every recipe in vanilla in the main tabs, as I can, because there are so many, it's very easy to forget some, so anyone can contribute more by making a pull request, as it's only 1 file to be edited (and you don't even need to make a modification, just explain) than by opening an issue that will distract from attention to other more important
