### ISSUE TITLE
Connection lost, invalid player data [forge,1.20.1]

### ISSUE THREAD

**Issue by cs234477** [Wilyicaro/Legacy-Minecraft#533]
### Legacy4J Version

1.20.1

### Mod Loader Version

forge

### Bug/Glitch Occurrence Context

failure to enter world, error is "Connection lost, invalid player data" and kept returning to menu.

### Crash Report

no crash report

### What happened wrong?

I tried to play the mod and load into a new world, and it keeps booting me back to the menu saying "Connection lost, invalid player data", I'm not sure what to do to fix it.

**Comment by TheAwesome98-Real** [comment]
also happens on fabric. can repro if i load a tutorial world after changing my gamemode

**Comment by Cjnator38** [comment]
had this happen when switching gamemodes as well

**Comment by TheAwesome98-Real** [comment]
> had this happen when switching gamemodes as well

my theory is that since java doesn't have a way to change gamemode, legacy4j modifies the level.dat (probably in memory), but it does so wrongly. my current workaround (since i'm only trying to load the tutorial world) is to enable host privileges and change my gamemode in the select menu (i don't know how this menu is called, it's where the player list and host options are)

**Comment by Wilyicaro** [comment]
Fixed in version 1.7.3, thanks for reporting.

**Comment by MelrikBirchJr** [comment]
It's not working for 1.7.4 I believe it's the same problem also for forge 1.20.1

**Comment by Wilyicaro** [comment]
Nope, it's working correctly

**Comment by Butterscotch-P1e** [comment]
I'm still having this issue on 1.8.6-lts
