### ISSUE TITLE
[Bug/Glitch] [1.21.1] Strange L4J behavior with mod-pack, might be driver related??

### ISSUE THREAD

**Issue by Cixon** [Wilyicaro/Legacy-Minecraft#581]
### Legacy4J Version

1.21-1.7.2-neoforge

### Mod Loader Version

NeoForge 21.1.35

### Crash upon client start-up phase.

Issue no longer persists **when disabling L4J and legacyskins-0.5.7+neoforge+1.21.1.jar** .

### Crash Report

https://gist.github.com/Cixon/b1400e211de1a7d5eac7388ba14b0beb

### What happened wrong?

Strange behavior occurs when attempting to launch my mod-pack that didn't occur before. Blames on L4J?

Context:
I've been building my mod-pack with L4J for sometime and never had a issue, I recently uploaded a stable build last night that I tested before going to bed and called it a day, today (09/02/24), it no longer works?

I did reinstall a controller driver on my computer when having issues with a emulator but this should be unrelated.. maybe?

Anyways, here's the log (ln276):
https://gist.github.com/Cixon/aec267e61b5503d683bc66c2ded2a9fa

Here's modpack:
https://modrinth.com/modpack/project-4j/version/1.0.9

**Comment by Wilyicaro** [comment]
As I said on Discord, this is not caused by Legacy4J, but rather by the game not starting properly, the controller manager is used before Legacy4J actually starts, without having set a value yet, resulting in the crash. 
I won't tell you exactly what you should do to fix this, as it requires testing, but I can simply make the controller manager have a value before the mod starts in 1.7.3 (which is not the proper fix, just a workaround)
