### ISSUE TITLE
biome_overrides.json water color and transparency are ignored when Sodium mod is installed

### ISSUE THREAD

**Issue by AgentMindStorm** [Wilyicaro/Legacy-Minecraft#59]
With Sodium:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/7bb58757-3f58-432a-879f-de8dfe0e38da)
Without Sodium:
![2024-01-25_08 55 32](https://github.com/Wilyicaro/Legacy-Minecraft/assets/101267493/a417914d-7f3d-4fc7-bf9b-dcf78541baea)

The underwater fog colors still work with Sodium, but the surface color and transparency always use the default colors.

Full mod list:

architectury-11.0.11-fabric
fabric-api-0.95.1+1.20.4
Minecraft-Legacy-1.20.4-1.3.2-fabric
sodium-fabric-mc1.20.3-0.5.5

Side note — this is not related to my previous report about ImmediatelyFast being incompatible. I solved that bug by creating a new, clean instance. This is a mod compatibility issue.

**Comment by Wilyicaro** [comment]
Unfortunately, even with some workarounds, Sodium uses the alpha for the lighting of the water too (for some reason), so the water transparency with sodium is broken, because the difference of light/transparency causes this blending issue:
![image](https://github.com/Wilyicaro/Legacy-Minecraft/assets/81383021/57c6e4fd-2e5d-4579-b7d1-b4d4a2fcb48f)

**Comment by Wilyicaro** [comment]
But the water color with this fix works well

**Comment by Wilyicaro** [comment]
Fixed in version 1.3.3, there are some incompatibilities with newer versions of the Fabric API.
