### ISSUE TITLE
Modrinth changelogs formatting issues

### ISSUE THREAD

**Issue by Poopooracoocoo** [Wilyicaro/Legacy-Minecraft#76]
https://modrinth.com/mod/legacy-minecraft/version/1.20.2-1.3.2+fabric

Changelogs are fine on CurseForge. https://www.curseforge.com/minecraft/mc-mods/legacy-minecraft/files/5058361

Another thing I noticed is that changelogs for every release are there. This makes using Modrinth's own changelog page difficult, but redundant. Not an issue though. 

Also I'm rather surprised to see you don't use GitHub Actions to build and publish. MC-Publish is quite popular, for example.

**Comment by Wilyicaro** [comment]
The changelog formatting is the same in both platforms, the problem is the different visuals of markdown with the same "arguments", and the changelogs for pratically every release are my mistake, but I don't think this gets in the way of something, only redundant as you said.
And about the Github Actions, I don't use it because I think it can make me post versions unnecessarily, I usually make a lot of mistakes lol
