### ISSUE TITLE
Add compatibility with Fancy Menus/Drippy Loading Screens?

### ISSUE THREAD

**Issue by ShatterdPotato** [Wilyicaro/Legacy-Minecraft#77]
Compatability with both mods would be nice, because then with the slide show mod you could recreate the loading screen of legacy console.

**Comment by Wilyicaro** [comment]
The intro/slides screen from LE is a planned feature, it'll be a option enabled by default, but the compatibility with fancy menus/drippy loading screens is almost impossible and unnecessary, because Legacy4J is a standalone mod with many changes in the game, including the modified screens of these mods.
However, I don't know if I completely remove the in-Game resource loading screen or if I use the loading screen from LE as replacement.
